altura = int(input("Digite a altura do retângulo "))
base = int3(input("Digite a base do retângulo "))
area = (altura*base)
perimetro = (altura+base)
print ("A área do retângulo é",area,"O perímetro do retângulo é",perimetro)